# Generated by Django 4.2.1 on 2023-05-23 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('asset_ID', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('Responsible_Employee_ID', models.IntegerField(default=0)),
                ('asset_name', models.CharField(max_length=100)),
                ('type_asset', models.CharField(max_length=100)),
                ('specifications_asset', models.CharField(max_length=200)),
                ('assigned_employee_asset', models.IntegerField(default=0)),
                ('storage_location_asset', models.CharField(max_length=200)),
                ('storage_features_assets', models.CharField(max_length=200)),
                ('current_act', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BaseActs',
            fields=[
                ('act_ID', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('responsible_employee_ID', models.IntegerField(default=0)),
                ('asset_ID', models.IntegerField(default=0)),
                ('numbers_act', models.IntegerField(default=0)),
                ('last_act', models.IntegerField(default=0)),
                ('data_start_act', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('employee_ID', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('personal_data_worker', models.CharField(max_length=200)),
                ('position_worker', models.CharField(max_length=100)),
                ('higher_worker', models.CharField(max_length=100)),
                ('work_department_worker', models.CharField(max_length=100)),
                ('access_rights_worker', models.CharField(max_length=200)),
                ('employee_location_worker', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hozoffice.question')),
            ],
        ),
    ]
